image: docker:19.03.6

variables:
  DOCKER_TLS_CERTDIR: "/certs"
  ARTIFACTS_DIR: artifacts

services:
  - docker:19.03.6-dind

before_script:
  - docker info
  - pwd
  - ls

maturin-build-dind:
  stage: build
  script:
    - docker run --rm -v $(pwd):/io --entrypoint '/bin/sh' konstin2/maturin:master -c 'rustup default nightly; maturin build -o artifacts' # Hard-Coded Artifacts dir
    # - docker run --rm -v $(pwd):/io konstin2/maturin:master build -o ${OUTPUT_PATH}
  artifacts:
    name: "$CI_BUILD_NAME"
    paths:
      - ${ARTIFACTS_DIR}
    expire_in: 1 week
  