image: docker:19.03.7

variables:
  DOCKER_TLS_CERTDIR: "/certs"
  ARTIFACTS_DIR: artifacts

services:
  - docker:19.03.7-dind

stages:
  - build
  - deploy

before_script:
  - docker info
  - pwd
  - ls

maturin-build-dind:
  stage: build
  script:
    - docker run --rm -v $(pwd):/io --entrypoint '/bin/sh' konstin2/maturin:master -c 'rustup default nightly; maturin build -o artifacts' # Hard-Coded Artifacts dir
    # - docker run --rm -v $(pwd):/io konstin2/maturin:master build -o ${OUTPUT_PATH}
  artifacts:
    name: "$CI_BUILD_NAME"
    paths:
      - ${ARTIFACTS_DIR}
    expire_in: 1 week

cargo-doc-build:
  stage: build
  script:
    - docker run --rm -v $(pwd):/io --entrypoint '/bin/sh' konstin2/maturin:master -c 'yum install -y git; rustup default nightly; cargo doc --no-deps' # to target/doc
  artifacts:
    name: "$CI_BUILD_NAME-doc"
    paths:
      - target/doc
    expire_in: 1 week

cargo-doc-deploy:
  image: go:latest
  stage: deploy
  script:
    - ls
    - git clone https://LER0ever:$GITLAB_GIT_TOKEN@gitlab.com/rongyi.io/configurations/websites/HPGO.rongyi.io.git
    - git config --global user.email "i@rongyi.io"
    - git config --global user.name "LER0ever"
    - cd HPGO.rongyi.io
    - rm -rf *
    - cp -r ../target/doc/* .
    - echo '<!DOCTYPE html><html><head><meta http-equiv="Refresh" content="0; url=/HPGO" /></head><body></body></html>' > index.html
    - git add -A
    - git diff-index --quiet HEAD || git commit -m "HPGO Rust Docs | Auto Deploy | $CI_SERVER_NAME $CI_PIPELINE_ID"
    - git push
