trigger:
    branches:
      include: ['*']
    tags:
      include: ['*']
  
jobs:
  - job:
    displayName: manylinux
    pool:
      vmImage: 'ubuntu-latest'
  
    steps:
      - script: |
          curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain nightly
          echo "##vso[task.setvariable variable=PATH;]$PATH:$HOME/.cargo/bin"
          rustup default nightly-x86_64-unknown-linux-gnu
          cargo --version
        displayName: "Install Rust"
      
      - bash: |
          MY_TAG="$(Build.SourceBranch)"
          MY_TAG=${MY_TAG#refs/tags/}
          echo $MY_TAG
          echo "##vso[task.setvariable variable=build.my_tag]$MY_TAG"
        displayName: "Create tag variable"
      
      - bash: |
          DATE="$(date +%Y-%m-%d)"
          echo "##vso[task.setvariable variable=build.date]$DATE"
        displayName: "Create date variable"

      - task: UsePythonVersion@0
        inputs:
          versionSpec: '3.8'
          architecture: 'x64'
    
      - script: |
          python -m pip install --upgrade pip setuptools wheel
        displayName: 'Upgrade Python pip'
    
      - bash: |
          python -m pip install maturin
        displayName: "Install Maturin via pip"

      - script: |
          maturin build -o $(Build.BinariesDirectory)
        displayName: 'Maturin build'
  
      - script: |
          pip install $(Build.BinariesDirectory)/HPGO-*-cp38-*.whl
        displayName: 'Install new wheel'

      - task: CopyFiles@2
        inputs:
          sourceFolder: $(Build.BinariesDirectory)
          contents: '**'
          targetFolder: $(Build.ArtifactStagingDirectory)
      
      - task: PublishBuildArtifacts@1
        inputs:
          pathToPublish: $(Build.ArtifactStagingDirectory)
          artifactName: LinuxWheel
      
      - script: |
          maturin publish -u rongyi -p "$(pypi.password)"
        displayName: "Upload to PyPi"
        condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/'))
  
  
  - job:
    displayName: macOS
  
    pool:
      vmImage: 'macOS-latest'
  
    steps:
      - script: |
          curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain nightly
          echo "##vso[task.setvariable variable=PATH;]$PATH:$HOME/.cargo/bin"
          rustup default nightly
        displayName: "Install Rust"
      
      - bash: |
          MY_TAG="$(Build.SourceBranch)"
          MY_TAG=${MY_TAG#refs/tags/}
          echo $MY_TAG
          echo "##vso[task.setvariable variable=build.my_tag]$MY_TAG"
        displayName: "Create tag variable"
      
      - bash: |
          DATE="$(date +%Y-%m-%d)"
          echo "##vso[task.setvariable variable=build.date]$DATE"
        displayName: "Create date variable"
  
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '3.8'
          architecture: 'x64'
    
      - script: |
          python -m pip install --upgrade pip setuptools wheel
        displayName: 'Upgrade Python pip'

      - bash: |
          python -m pip install maturin
        displayName: "Install Maturin via pip"
  
      - script: |
          maturin build -o $(Build.BinariesDirectory)
        displayName: 'Maturin build'
  
      - script: |
          pip install $(Build.BinariesDirectory)/HPGO-*-cp38-*.whl
        displayName: 'Install new wheel'

      - task: CopyFiles@2
        inputs:
          sourceFolder: $(Build.BinariesDirectory)
          contents: '**'
          targetFolder: $(Build.ArtifactStagingDirectory)
      
      - task: PublishBuildArtifacts@1
        inputs:
          pathToPublish: $(Build.ArtifactStagingDirectory)
          artifactName: MacOSWheel
      
      - script: |
          maturin publish -u rongyi -p "$(pypi.password)"
        displayName: "Upload to PyPi"
        condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/'))
  
  
  - job: 
    displayName: Windows
  
    pool:
      vmImage: 'windows-latest'
  
    steps:
      - script: |
            curl -sSf -o rustup-init.exe https://win.rustup.rs
            rustup-init.exe -y --default-host x86_64-pc-windows-msvc --default-toolchain nightly
            echo "##vso[task.setvariable variable=PATH;]%PATH%;%USERPROFILE%\.cargo\bin"
            rustup default nightly-x86_64-pc-windows-msvc
            cargo --version
        displayName: Install Rust
      
      - bash: |
          MY_TAG="$(Build.SourceBranch)"
          MY_TAG=${MY_TAG#refs/tags/}
          echo $MY_TAG
          echo "##vso[task.setvariable variable=build.my_tag]$MY_TAG"
        displayName: "Create tag variable"
      
      - bash: |
          DATE="$(date +%Y-%m-%d)"
          echo "##vso[task.setvariable variable=build.date]$DATE"
        displayName: "Create date variable"
  
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '3.8'
          architecture: 'x64'
  
      - script: |
          python -m pip install --upgrade pip setuptools wheel
        displayName: 'Upgrade Python pip'

      - script: |
          python -m pip install maturin
        displayName: "Install Maturin via pip"
  
      - script: |
          maturin build -o $(Build.BinariesDirectory) --interpreter python
        displayName: 'Maturin build'
  
      - powershell: |
          pip install $(Build.BinariesDirectory)/$(Get-ChildItem $(Build.BinariesDirectory)/HPGO-*-cp38-*.whl | Select -exp Name)
        displayName: 'Install new wheel'

      - task: CopyFiles@2
        inputs:
          sourceFolder: $(Build.BinariesDirectory)
          contents: '**'
          targetFolder: $(Build.ArtifactStagingDirectory)
      
      - task: PublishBuildArtifacts@1
        inputs:
          pathToPublish: $(Build.ArtifactStagingDirectory)
          artifactName: Win32Wheel
      
      - script: |
          maturin publish -u rongyi -p "$(pypi.password)" --interpreter python
        displayName: "Upload to PyPi"
        condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/'))
