[package]
name = "HPGO"
version = "0.9.0"
license = "Apache"
authors = ["Yi Rong <i@rongyi.io>"]
description = "Hybrid Parallelism Global Orchestration"
repository = "https://github.com/LER0ever/HPGO"
exclude = [
    "examples/*"
]

[lib]
name = "HPGO"
path = "src/lib.rs"
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "HPGO-CMD"
path = "src/main.rs"

[features]
# If enabled, it produces a Python module.
python-module = ["pyo3", "numpy"]

[dependencies]
docopt = "1"
itertools = "0.7.8"
serde = { version = "1.0.70", features = ["derive"] }
csv = "1.0.0"
ordered-float = "0.5.0"
float-cmp = "0.5.2"
strsim = "0.9.1"
ndarray = "0.13.0"
pyo3 = { version = "0.8.2", features = ["extension-module"], optional = true }
numpy = { version = "0.7.0", optional = true }

[dev-dependencies]
rustlearn = "0.5.0"
bencher = "0.1.5"
