name: Rust

on: [push]

jobs:
  check:
    name: HPGO Rust Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            override: true

      - name: Run cargo build
        uses: actions-rs/cargo@v1
        with:
          command: build